### PR TITLE
Add read filtering and taxonomic classification Snakefiles + singularity

### PR DESCRIPTION
**Pull request by charlesreid1**
This PR adds a read filtering Snakefile and a taxonomic classification Snakefile.

Snakefiles are currently contained in the `workflows/` directory, under the respective `read_filtering/` and `taxonomic_classification/` directories.

We will consolidate these Snakefiles in a future pull request, this PR simply adds the new Snakefiles.

#### Merge Checklist

- [x] Typos are a sign of poorly maintained code. Has this request been checked with a spell checker?
- [x] ~Tutorials should be universally reproducible. If this request modifies a tutorial, does it assume we're starting from a blank Ubuntu 16.04 (Xenial Xerus) image?~ no changes to tutorials. that's happening in the `documentation/` branch.
- [x] ~Large diffs to binary or data files can artificially inflate the size of the repository. Are there large diffs to binary or data files, and are these changes necessary?~ no officer, nothing to see here, no large binary files, none whatsoever -

### CODE REVIEW

**Comment by charlesreid1** [comment]
Remaining to do:
* Test this puppy out with latest singularity
* Create singularity test matrix for workflows
* Fix header+comments in Snakefile
* Move README to ReadFilteringWalkthrough.md or TaxClassWalkthrough.md
* Add a README that explains a bit more about this particular workflow

**Comment by charlesreid1** [comment]
Workflows are all tested and working. Some remaining things to work out:
* What build targets (the "ghost" make all rules) shall we provide for our users?
  * More specifically, there are obvious end objectives the user will want, but there may be intermediate stops along the way the user will also want
  * Example: I want to build a local custom database for taxonomic classification, and that's it (leave out the sourmash/kaiju step)
* We have a way to set multiple parameter defaults - what values shall we use? (in progress)

**Comment by charlesreid1** [comment]
todo:
* custom singularity (from dockerfile)
* split default params + user params

**Comment by charlesreid1** [comment]
**Current status:** working through a problem with the Kaiju step (everything else is ok). This doesn't appear to be a problem with the workflow since the step was tested and working a month ago. Will report back with more info.

This branch still keeps Snakefiles for each workflow separate. For now, the tax. class. Snakefile lives in the `tax_class` folder, along with a `taxonomic_classification.settings` file containing default parameter values for that workflow.

The plan is to combine all of the settings files into a single default parameter/config in a separate pull request, once we have more workflows completed and merged.

**Comment by brooksph** [comment]
@charlesreid1 did using an updated/different link fix the database issue?

**Comment by charlesreid1** [comment]
This task is currently in progress... I will have more to report shortly.

**Comment by charlesreid1** [comment]
The kaiju step has been chugging along for about 1 hour using the proGenomes database from http://kaiju.binf.ku.dk/server (it was previously crashing after about 2 minutes) so this appears to be a problem specific to the NCBI BLAST nr +euk database tar file.

(Using the parameters file, it was pretty easy to swap out the kaiju database file used.)

I'll continue to let this run and test out the last pieces (krona), then this Snakefile will be finished nad the PR will be ready to merge.

**Comment by charlesreid1** [comment]
kaiju finished successfully twice so far (run with two pairs of read files as inputs). There's still some digging to do into why the database file with eukaryotes is not working, but at least we've managed to isolate the issue to a particular database file.

**Comment by brooksph** [comment]
Closed in favor of https://github.com/dahak-metagenomics/dahak/pull/95

**Comment by charlesreid1** [comment]
closed, as #95 adds these commits plus others and has been merged

**Pull request closed without merging**
